import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hygenie</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href="#" className="scrolltop" id="scroll-top">
        <i className="bx bx-up-arrow-alt scrolltop__icon"></i>
      </a>

      <header className="l-header" id="header">
        <nav className="nav bd-container">
          <a href="#home" className="nav__logo">
            <img src="/img/logo.png" alt="" />
          </a>

          <div className="nav__menu" id="nav-menu">
            <ul className="nav__list">
              <li className="nav__item">
                <a href="#about" className="nav__link ">
                  About
                </a>
              </li>
              <li className="nav__item">
                <a href="#theme" className="nav__link ">
                  {" "}
                  Goal{" "}
                </a>
              </li>
              <li className="nav__item">
                <a href="#timeline" className="nav__link">
                  Timeline
                </a>
              </li>
              <li className="nav__item">
                <a href="#events" className="nav__link">
                  Features
                </a>
              </li>
              <li className="nav__item">
                <a href="#team" className="nav__link">
                  Team
                </a>
              </li>
              <li className="nav__item">
                <Link href="/search" className="nav__link">
                  Search
                </Link>
              </li>
              <li>
                <i
                  className="bx bx-toggle-left change-theme"
                  id="theme-button"
                ></i>
              </li>
            </ul>
          </div>

          <div className="nav__toggle" id="nav-toggle">
            <i className="bx bx-grid-alt"></i>
          </div>
        </nav>
      </header>

      <main className="l-main">
        <section className="home" id="home">
          <div className="home__container bd-container bd-grid">
            <div className="home__img">
              <img src="/img/toilet.png" alt="" />
            </div>

            <div className="home__data">
              <h1 className="home__title">Welcome to Hygenie 🫧</h1>
              <p className="home__description">
                Discover the cleanest and safest public restrooms nearby with
                our app, so you can take care of your needs without any worry or
                hassle
              </p>
              <Link href="/search">
                <button className="button">Search</button>
              </Link>
            </div>
          </div>
        </section>

        <section className="share section bd-container" id="about">
          <div className="share__container bd-grid">
            <div className="share__data">
              <h2 className="section-title-center">
                About <br /> Hygenie 🧼{" "}
              </h2>
              <p className="share__description">
                Introducing our revolutionary app built at Google Solution
                Challenge23 that makes finding clean and safe public restrooms
                easier than ever before! With features like multilingual
                support, privacy protection, and emergency assistance, our app
                is the ultimate companion for all your restroom needs. It even
                provides tips on sustainable restroom usage and lets users
                contribute photos and report issues. Our app also offers
                real-time updates on availability and cleanliness, along with
                information on amenities and accessibility for people with
                disabilities. Plus, with location-based offers and event-based
                queue length indicators, our app ensures a comfortable and
                hassle-free restroom experience.{" "}
              </p>
            </div>

            <div className="share__img">
              <img src="/img/location.png" alt="" />
            </div>
          </div>
        </section>

        <section className="share section bd-container" id="theme">
          <div className="share__container bd-grid">
            <div className="share__data">
              <img src="/img/SDG 6.png" alt="" />
            </div>
            <div className="share__img about__GDSC">
              <h2 className="section-title-center">
                United Nations SDG 6: Clean Water and Sanitation🌍
              </h2>
              <p className="share__description">
                Ensuring access to safe and affordable water and sanitation
                facilities for all to promote health and well-being.
              </p>
            </div>
          </div>
        </section>

        <section className="decoration section bd-container" id="events">
          <h2 className="section-title">Features</h2>
          <div className="decoration__container bd-grid">
            <div className="decoration__data">
              <img
                src="/img/equipment.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">Amenities Information</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                Provides information on the availability of amenities like soap,
                hand sanitizer, and toilet seat covers.
              </p>
            </div>
            <div className="decoration__data">
              <img
                src="/img/accessibility.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">Accessibility Information</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                Provides information on the accessibility of restrooms for
                people with disabilities.
              </p>
            </div>
            <div className="decoration__data">
              <img
                src="/img/emergency.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">Emergency Assistance</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                In case of emergency, users can easily connect with nearby
                emergency services.
              </p>
            </div>
            <div className="decoration__data">
              <img
                src="/img/photo.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">User-Contributed Photos</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                Users contributed photos to help others assess the cleanliness
                and safety of restrooms.
              </p>
            </div>
            <Link href="https://gauri.yaga.cf/">
            <div className="decoration__data">
              <img
                src="/img/update.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">Real-time Updates</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                Provides real-time updates on the availability and cleanliness
                of nearby restrooms.
              </p>
            </div>
            </Link>
            <Link href="https://deekshita-geeksforgeeks.glitch.me/">
            <div className="decoration__data">
              <img
                src="/img/coupon.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">Get Discount Coupons with AR for Contributions</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
               Whenever a user contributes a review or a report, they get discount coupons from popular brands.
              </p>
            </div>
            </Link>
            <div className="decoration__data">
              <img
                src="/img/lingual.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">Multilingual Support</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                Supports multiple languages, making it accessible to users
                worldwide.
              </p>
            </div>
            <div className="decoration__data">
              <img
                src="/img/baby.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">
                Baby Changing Facility Indicator
              </h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                Indicates the availability of baby changing facilities in
                restrooms.
              </p>
            </div>
            <div className="decoration__data">
              <img
                src="/img/eco.png"
                alt=""
                className="decoration__img"
                id="apple_render"
              />
              <h3 className="decoration__title">
                Eco-friendly Toilet Indicator
              </h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>
                Indicates the availability of eco-friendly toilet facilities.
              </p>
            </div>
          </div>
        </section>

        {/* <section id="sponsor" className="decoration section"> */}
        {/*   <div className="sponsor-container "> */}
        {/*     <h1 className="section-title">Supporting Organisation</h1> */}
        {/*     <section className="decoration__data"> */}
        {/*       <div className="slide"><a title="RCND" href="https://www.instagram.com/rc_newdelhi/"><img src="./img/RCND.jpg" alt="" /></a></div> */}
        {/*     </section> */}
        {/*   </div> */}
        {/* </section> */}

        <section className="decoration section bd-container" id="team">
          <h2 className="section-title">Team</h2>
          <div className="decoration__container bd-grid team-grid">
            <div className="decoration__data team_data">
              <img
                src="/img/Team/pooja_gera.jpg"
                alt=""
                className="decoration__img"
                id="team_render"
              />
              <h3 className="decoration__title">Pooja Gera</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>Web, Firebase, Tensorflow, Google Cloud</p>
            </div>
            <div className="decoration__data team_data">
              <img
                src="/img/Team/Gaurisha_R_Srivastava - Gaurisha R Srivastava.jpg"
                alt=""
                className="decoration__img"
                id="team_render"
              />
              <h3 className="decoration__title">Gaurisha R. Srivastava</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>Web, Firebase, Tensorflow</p>
            </div>
            <div className="decoration__data team_data">
              <img
                src="/img/Team/deekshita.jpeg"
                alt=""
                className="decoration__img"
                id="team_render"
              />
              <h3 className="decoration__title">Deekshita Verma</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>Augmented Reality, Web</p>
            </div>
            <div className="decoration__data team_data">
              <img
                src="/img/Team/Sanskriti_Agarwal - Sanskriti Agarwal.jpg"
                alt=""
                className="decoration__img"
                id="team_render"
              />
              <h3 className="decoration__title">Sanskriti Agarwal</h3>
              {/* <!--<a href="./view/designsolve.html" className="button button-link">Details</a>--> */}
              <p>Figma, Web, Firebase</p>
            </div>
          </div>
        </section>

        <section className="footer " id="contact_us">
          <div className="footer__container bd-container bd-grid">
            <div className="footer__social">
              <h2 className="text-white footer__title">
                Built at Solve for India Challenge 2023
              </h2>
              <h3 className="footer__title text-white">&#169; Celestial Biscuit</h3>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
