import { type NextPage } from "next";
import Head from "next/head";
import { HiSearch } from "react-icons/hi";
import { type SyntheticEvent, useEffect, useState } from "react";
import axios from "axios";
import { type Washroom } from "@/types/washroom";
import Card from "@/components/card";
import Link from "next/link";

const Home: NextPage = () => {
  const [latitude, setLatitude] = useState<number | null>(null);
  const [longitude, setLongitude] = useState<number | null>(null);
  const [datafromapi, setDatafromapi] = useState<Washroom[]>();
  const [datafromsearch, setDatafromsearch] = useState<Washroom[]>();
  const [search, setSearch] = useState<string>("");

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setLatitude(position.coords.latitude);
          setLongitude(position.coords.longitude);
        },
        (error) => {
          console.error(error);
        }
      );
    } else {
      console.error("Geolocation is not supported by this browser.");
    }
  }, []);

  async function getDataFromApi() {
    const somedata = await axios.post<Washroom[]>("/api/getdata", {
      latitude: latitude,
      longitude: longitude,
    });
    setDatafromapi(somedata.data);
  }

  useEffect(() => {
    if (!longitude || !latitude) return;
    void getDataFromApi();
  }, [latitude, longitude]);

  async function onSeach(e: SyntheticEvent) {
    e.preventDefault();
    const res = await axios.post<Washroom[]>("/api/searchdata", {
      search: search,
    });
    setDatafromsearch(res.data);
  }

  return (
    <>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="l-header" id="header">
        <nav className="nav bd-container">
          <a href="#home" className="nav__logo">
            <img src="/img/logo.png" alt="" />
          </a>

          <div className="nav__menu" id="nav-menu">
            <ul className="nav__list">
              <li className="nav__item">
                <a href="index.html" className="nav__link ">
                  Home
                </a>
              </li>
              <li className="nav__item">
                <a href="search.html" className="nav__link active">
                  Search
                </a>
              </li>
              <li>
                <i
                  className="bx bx-toggle-left change-theme"
                  id="theme-button"
                ></i>
              </li>
            </ul>
          </div>

          <div className="nav__toggle" id="nav-toggle">
            <i className="bx bx-grid-alt"></i>
          </div>
        </nav>
      </header>

      <section className="search" id="search">
        <div className="search__container bd-container ">
          <div className="search__data location">
            <div className="image-loc">
              <h2 className="search__title">Want to find toilets nearby?</h2>
              <button id="search-input-location" className="button-white">
                Search{" "}
              </button>
            </div>
          </div>

          <div className="search__container-cards bd-container bd-grid">
            <div className="search__data search__location">
              <div id="search-results-location">
                {datafromapi &&
                  datafromapi.map((washroom, index) => (
                    <Link href={`/washroom/${washroom.id}`} key={index}>
                      <Card props={washroom} />
                    </Link>
                  ))}
              </div>
            </div>
          </div>

          <div className="search__data search__name">
            <h2 className="search__title">Search by Name</h2>
            <div className="flex items-center justify-center">
              <input
                type="text"
                id="search-input-title"
                placeholder="Search by Name"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
              <span
                onClick={(e) => void onSeach(e)}
                className="pb-2 text-3xl font-bold"
              >
                <HiSearch className="mb-3 ml-2" />
              </span>
            </div>
            <div id="search-results-title">
              {datafromsearch &&
                datafromsearch.map((washroom, index) => (
                  <Link href={`/washroom/${washroom.id}`} key={index}>
                  <Card props={washroom} />
                  </Link>
                ))}
            </div>
          </div>
        </div>
      </section>
      <section className="footer " id="contact_us">
          <div className="footer__container bd-container bd-grid">
            <div className="footer__social">
              <h2 className="text-white footer__title">
                Built at Solve for India Challenge 2023
              </h2>
              <h3 className="footer__title text-white">&#169; Celestial Biscuit</h3>
            </div>
          </div>
        </section>
    </>
  );
};

export default Home;
